### PR TITLE
feat(alternarts): add archaeopteryx alternart

### LINKED ISSUE #25: Release The First Alternart Asset
Is your feature request related to a problem? Please describe.
/

Describe the solution you'd like
Release the first alternart asset in order to complete an example flow to be shown to contributors.

Describe alternatives you've considered
/

Additional context
/

### PR DESCRIPTION
**Pull request by MarcoDoC**
# Pull Request

### This PR is labeled as:
*Choose only one and remember to select the label even on the right.*

- [x] Feature
- [ ] Bug
- [ ] Other

### This PR has the following linked issues:
- Closes #25;

### My solution is explained as follows:
Adds archaeopteryx alternart into alternarts folder.

### CODE REVIEW

**Review by airscripts — CHANGES_REQUESTED** [review]
In order to make this mergeable, remove the '-3' at the end of the filename.

**Comment by airscripts** [comment]
> In order to make this mergeable, remove the '-3' at the end of the filename.

Lastly, make alternart folder name plural.

**Comment by MarcoDoC** [comment]
both done

**Review by airscripts — APPROVED** [review]
LGTM.

**Pull request merged**
