### PR TITLE
feat: add cover images

### LINKED ISSUE #19: Create Collection Cover Image
**Is your feature request related to a problem? Please describe.**
/

**Describe the solution you'd like**
Create a collection cover image that will be used in ```README.md```, as Open Graph image, etc.  
The image need to have a resolution of 1280x640px.  

**Describe alternatives you've considered**
/

**Additional context**
/

### PR DESCRIPTION
**Pull request by MarcoDoC**
# Pull Request
Compile all the information written below to send a legitimate pull request to the repository!

### This PR is labeled as:
*Choose only one and remember to select the label even on the right.*

- [ ] Feature
- [ ] Bug
- [x] Other

### This PR has the following linked issues:
- Closes #19;

### My solution is explained as follows:
Creates a cover image for the README.md.

### CODE REVIEW

**Comment by airscripts** [comment]
The cover images look good. Nice work on this!  
I just ask you to put them into ```assets/images``` with these two names: ```cover.png``` and ```large-cover.png```.

**Comment by MarcoDoC** [comment]
done!

**Comment by airscripts** [comment]
> done!

Looks good. I think we should only change the watermark and it is ready to be merged.

**Comment by MarcoDoC** [comment]
done!

**Comment by airscripts** [comment]
> done!

Is the .xcf file put there voluntarily?

**Comment by MarcoDoC** [comment]
yes, it's the layered version (in GIMPP format) to be able to move the signature if needed

**Comment by airscripts** [comment]
LGTM.

**Pull request merged**
