### PR TITLE
feat(raw): add giganotosaurus asset

### PR DESCRIPTION
**Pull request by GuidoPenta**
# Pull Request

### This PR is labeled as:
*Choose only one and remember to select the label even on the right.*

- [x] Feature
- [ ] Bug
- [ ] Other

### This PR has the following linked issues:
- Closes /;

### My solution is explained as follows:
Adds Giganotosaurus raw asset.

### CODE REVIEW

**Review by airscripts — CHANGES_REQUESTED** [review]
The asset is placed correctly inside the collection.  
The only thing that you have to do, is to add the number of generations needed to obtain this asset inside ```collection.md```.  
Lastly, write me down in a comment here the prompt used. I'll be adding it to the specific file that we use for track them down.

**Comment by GuidoPenta** [comment]
ok, I've opened another PR to update the collection.md file, adding the number of generations needed.

I've used Stable Diffusion using the prompt "giganotosaurus in baroque style".

Thank you!

**Review by airscripts — APPROVED** [review]
LGTM.

**Comment by GuidoPenta** [comment]
fwpraj-fwp

**Review by MarcoDoC — COMMENTED** [review]
for the future I suggest to use a prompt more targeted to the painting art style to reduce incongruent assents, if you need help with prompts, feel free to ask

**Review by MarcoDoC — APPROVED** [review]

**Pull request merged**
