### PR TITLE
feat:  move e96a1fc4 to pure state

### LINKED ISSUE #9: Release First Pure Asset
**Is your feature request related to a problem? Please describe.**
/

**Describe the solution you'd like**
Release the first pure asset in order to complete an example flow to be shown to contributors.

**Describe alternatives you've considered**
/

**Additional context**
/

### PR DESCRIPTION
**Pull request by MarcoDoC**
# Pull Request

### This PR is labeled as:
*Choose only one and remember to select the label even on the right.*

- [ ] Feature
- [ ] Bug
- [x] Other

### This PR has the following linked issues:
- Closes #9;

### My solution is explained as follows:
Adds e96a1fc4 to pure state.

### CODE REVIEW

**Comment by airscripts** [comment]
Looking good.   
While we wait for our poll to end, let me ask you a question.   
Why did you put generations in the file that way? Wouldn't be better to just sum up the generations and leave 17?

**Comment by MarcoDoC** [comment]
I agree, but before "merging" the generations I'd like to talk about it with you, it'll be merged in next commit

**Comment by MarcoDoC** [comment]
PR is ready for me

**Review by airscripts — CHANGES_REQUESTED** [review]
The PR looks good to me.  
Before merging, rename the archaeopteryx in pure removing '-2' at the end of the filename.

**Comment by MarcoDoC** [comment]
done

**Review by airscripts — APPROVED** [review]
LGTM.

**Pull request merged**
